steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_WS_URL=${_NEXT_PUBLIC_WS_URL}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/echo-frontend'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/echo-frontend']
images:
  - 'gcr.io/$PROJECT_ID/echo-frontend'
